name: ci
on:
  push:
    branches:
      - "**"
  pull_request: {}
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-versions: 1.7
          cache: false

      - name: checkout
        uses: actions/checkout@v2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          args: --disable-all --enable=govet,errcheck,staticcheck,gosimple

      - name: test
        run: go test -v ./...
